# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ad76c21bdff576d25c0bfb5a2f697461fc2f680d129f16b6ef8916b6e2482f5214ce49c588fc3bfce696c11b3b6df0996f2769f203960969db7f89706c0f67

test:
  secret_key_base: dbc55b624665b8530f3aaf5d5cf1b4c339791350592d36f853ecfbb5cd6b11709872299fe121516c43761897780b47e0212ad4b033125022f936913853aea6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
